### ISSUE TITLE
Bug in commercial version of liquibase related to mongodb

### ISSUE THREAD

**Issue by aayoubb** [liquibase/liquibase-mongodb#420] opened 2023-08-10 07:12 UTC
Hi when I run a Liquibase update on Mongodb with Mongosh as a runner for a .js file I get an error
`Error parsing command line: unrecognised option --file`
and effectively the argument --file it is not a part of mongodb arguments this is coming from com.liquibase.ext.tools.MongoshRunner.createFinalCommandArray of liquibase-commercial-mongodb-1.x.x.jar
I am also wondering about the use of eval that was deprecated since the Mongodb 3 especially that liquibase-commercial-mongodb-1.x.x.jar is only compatible with mongodb4 and upper

```
if (this.outFile != null) {
                commandArray.add("--file");
                commandArray.add(this.outFile.getAbsolutePath());
            } else {
                commandArray.add("--eval");
                commandArray.add(this.sqlStrings[0].toSql());
            }
```

**Comment by vitaliimak** [comment] 2023-08-10 13:59
Hi @aayoubb 
Could you please explain your workflow? Could you describe the liquibase and extensions versions that you are using and give an example of a changelog and properties files?

The `--file` command line attribute is used according to the [write-scripts](https://www.mongodb.com/docs/mongodb-shell/write-scripts/#execute-a-script-from-the-command-line) MongoDB documentation.
You are right that `db.eval()` is deprecated - https://www.mongodb.com/docs/v4.2/reference/method/db.eval/ However, it isn't used in liquibase-commercial-mongodb. There are two different evals in MongoDB. The `--eval` in the `else` statement is a command line attribute https://www.mongodb.com/docs/mongodb-shell/reference/options/#std-option-mongosh.--eval

**Comment by aayoubb** [comment] 2023-08-10 15:33
Hi @vitaliimak

In my case I used Liquibase by command line `liquibase update` and docker image in both I got the same error.
Here the jar that I used

- liquibase-mongodb-4.21.0.jar
- mongodb-driver-core-4.8.2.jar
- mongodb-driver-sync-4.8.2.jar
- bson-4.8.2.jar

And I tried to respect the compatibility between the jar. I chose the liquibase v4.21 instead of the last one (v4.23) because the latter has a bug https://forum.liquibase.org/t/liquibase-mongodb-extension-issue/8403

here my mongodb version 
![image](https://github.com/liquibase/liquibase-mongodb/assets/9989048/a3871af5-7807-4cde-8554-e6aa51496d9a)

I pushed my liquibase project here https://github.com/aayoubb/LiquibaseTest/tree/main/officielExemple and I the putted the whole stacktrace here https://github.com/aayoubb/LiquibaseTest/blob/main/officielExemple/ErrorStack 

In the stacktrace I can see that liquibase launch the mongodb cmd 

```
[2023-08-10 17:25:32] INFOS [liquibase.change] mongosh command:
mongosh.exe mongodb://localhost:27017/pao --file C:\Temp\liquibase-.txt-orders-adeel-1628513974124174188.txt
```
And mongodb return the message 

```
 Error parsing command line: unrecognised option '--file'
try 'mongosh.exe --help' for more information

```
When I copy past the same command in mongosh I got the same error.

**Comment by vitaliimak** [comment] 2023-08-15 14:27
Hello @aayoubb 
I cannot reproduce this issue in my environment. My best guess is that your `mongosh` is outdated and doesn't support the `--file` option. Could you please run `mongosh.exe --version` in the console? If it shows a version less than 1.9.0 could you download and install the newest version https://www.mongodb.com/try/download/shell ?

**Comment by vitaliimak** [comment] 2023-08-16 09:29
@aayoubb 
Thank you for your suggestion, but this part of the extension is not open-source. However, we will think about your idea.
I am curious if your initial question has been resolved by updating to the latest versions of mongosh. Despite the fact that the `--file` option is not required it is supported by the latest mongosh and should work.

**Comment by aayoubb** [comment] 2023-08-16 09:55
@vitaliimak 
Yes when I add the mongosh v1.10.5 in the Path, the` liquibase update` works fine.

**Comment by vitaliimak** [comment] 2023-08-16 11:17
@aayoubb 
I'm glad things are working now. I'll close the issue, but feel free to re-open it if you find something else.

**Closed by vitaliimak** 2023-08-16 11:17 UTC
