### ISSUE TITLE
Is this extension crush with postgreSQL?

### ISSUE THREAD

**Issue by kooison** [liquibase/liquibase-mongodb#87] opened 2021-01-28 11:02 UTC
Originally I'm using liquibase to update postgresql, it just working fine.

However, when i try to update mongo too,  i added this jar file into lib folder, mongo can be updated.  But the postgresql no longer work...

    C:\Downloads\liquibase-4.2.2\postgresql>CALL ..\liquibase "--changeLogFile=template.xml" "--driver=org.postgresql.Driver" "--classpath=postgresql-42.2.18.jar" "--url=jdbc:postgresql://xxxxxxxxxx:5432/xxxxxxxxxx" "--username=xxxxxxxxxx" "--password=xxxxxxxxxx" "--logLevel=debug" update
    [2021-01-28 18:44:15] FINE [liquibase.servicelocator] Loaded liquibase.license.LicenseService instance liquibase.pro.license.keymgr.DaticalTrueLicenseService
    [2021-01-28 18:44:15] INFO [liquibase.integration] No Liquibase Pro license key supplied. Please set liquibaseProLicenseKey on command line or in liquibase.properties to use Liquibase Pro features.
    Liquibase Community 4.2.2 by Datical
    ####################################################
    ##   _     _             _ _                      ##
    ##  | |   (_)           (_) |                     ##
    ##  | |    _  __ _ _   _ _| |__   __ _ ___  ___   ##
    ##  | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \  ##
    ##  | |___| | (_| | |_| | | |_) | (_| \__ \  __/  ##
    ##  \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|  ##
    ##              | |                               ##
    ##              |_|                               ##
    ##                                                ##
    ##  Get documentation at docs.liquibase.com       ##
    ##  Get certified courses at learn.liquibase.com  ##
    ##  Free schema change activity reports at        ##
    ##      https://hub.liquibase.com                 ##
    ##                                                ##
    ####################################################
    Starting Liquibase at 18:44:15 (version 4.2.2 #36 built at 2020-12-09 20:07+0000)
    [2021-01-28 18:44:15] FINE [liquibase.integration] Adding 'file:/C:/Downloads/liquibase-4.2.2/postgresql/postgresql-42.2.18.jar' to the Java classpath.
    [2021-01-28 18:44:15] FINE [liquibase.integration] Liquibase Hub URL:      https://hub.liquibase.com
    [2021-01-28 18:44:15] FINE [liquibase.integration] Liquibase Hub Mode:     all
    [2021-01-28 18:44:15] FINE [liquibase.resource] Adding path C:\Downloads\liquibase-4.2.2\postgresql\. to resourceAccessor liquibase.resource.FileSystemResourceAccessor
    [2021-01-28 18:44:15] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.CockroachDatabase
    [2021-01-28 18:44:15] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.DB2Database
    [2021-01-28 18:44:15] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.Db2zDatabase
    [2021-01-28 18:44:15] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.DerbyDatabase
    [2021-01-28 18:44:15] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.Firebird3Database
    [2021-01-28 18:44:15] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.FirebirdDatabase
    [2021-01-28 18:44:15] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.H2Database
    [2021-01-28 18:44:15] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.HsqlDatabase
    [2021-01-28 18:44:15] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.InformixDatabase
    [2021-01-28 18:44:15] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.Ingres9Database
    [2021-01-28 18:44:15] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.MSSQLDatabase
    [2021-01-28 18:44:15] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.MariaDBDatabase
    [2021-01-28 18:44:15] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.MockDatabase
    [2021-01-28 18:44:15] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.MySQLDatabase
    [2021-01-28 18:44:15] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.OracleDatabase
    [2021-01-28 18:44:15] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.PostgresDatabase
    [2021-01-28 18:44:15] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.SQLiteDatabase
    [2021-01-28 18:44:15] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.SybaseASADatabase
    [2021-01-28 18:44:15] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.SybaseDatabase
    [2021-01-28 18:44:15] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.UnsupportedDatabase
    [2021-01-28 18:44:15] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.ext.mongodb.database.MongoLiquibaseDatabase
    [2021-01-28 18:44:15] FINE [liquibase.database] Properties:
    [2021-01-28 18:44:15] FINE [liquibase.database] Key:'password' Value:'**********'
    [2021-01-28 18:44:15] FINE [liquibase.database] Key:'user' Value:'xxxxxxxxxx'
    [2021-01-28 18:44:15] FINE [liquibase.database] Connecting to the URL:'jdbc:postgresql://xxxxxxxxxx:5432/xxxxxxxxxx' using driver:'org.postgresql.Driver'
    [2021-01-28 18:44:15] FINE [liquibase.servicelocator] Loaded liquibase.database.DatabaseConnection instance liquibase.database.jvm.JdbcConnection
    [2021-01-28 18:44:15] FINE [liquibase.servicelocator] Loaded liquibase.database.DatabaseConnection instance com.datical.liquibase.ext.database.jvm.ProJdbcConnection
    [2021-01-28 18:44:15] FINE [liquibase.servicelocator] Loaded liquibase.database.DatabaseConnection instance liquibase.ext.mongodb.database.MongoConnection
    Unexpected error running Liquibase: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Could not open connection to database: UNKNOWN
    For more information, please use the --logLevel flag
    [2021-01-28 18:44:15] SEVERE [liquibase.integration] Unexpected error running Liquibase: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Could not open connection to database: UNKNOWN
    liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Could not open connection to database: UNKNOWN
            at liquibase.integration.commandline.CommandLineUtils.createDatabaseObject(CommandLineUtils.java:131)
            at liquibase.integration.commandline.Main.doMigration(Main.java:1409)
            at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:361)
            at liquibase.Scope.lambda$child$0(Scope.java:160)
            at liquibase.Scope.child(Scope.java:169)
            at liquibase.Scope.child(Scope.java:159)
            at liquibase.Scope.child(Scope.java:138)
            at liquibase.Scope.child(Scope.java:222)
            at liquibase.Scope.child(Scope.java:226)
            at liquibase.integration.commandline.Main$1.run(Main.java:360)
            at liquibase.integration.commandline.Main$1.run(Main.java:193)
            at liquibase.Scope.child(Scope.java:169)
            at liquibase.Scope.child(Scope.java:145)
            at liquibase.integration.commandline.Main.run(Main.java:193)
            at liquibase.integration.commandline.Main.main(Main.java:156)
    Caused by: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Could not open connection to database: UNKNOWN
            at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:216)
            at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:175)
            at liquibase.database.DatabaseFactory.openDatabase(DatabaseFactory.java:140)
            at liquibase.integration.commandline.CommandLineUtils.createDatabaseObject(CommandLineUtils.java:96)
            ... 14 more
    Caused by: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Could not open connection to database: UNKNOWN
            at liquibase.database.ConnectionServiceFactory.create(ConnectionServiceFactory.java:36)
            at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:213)
            ... 17 more
    Caused by: liquibase.exception.DatabaseException: Could not open connection to database: UNKNOWN
            at liquibase.ext.mongodb.database.MongoConnection.open(MongoConnection.java:104)
            at liquibase.database.ConnectionServiceFactory.create(ConnectionServiceFactory.java:33)
            ... 18 more
    Caused by: java.lang.IllegalArgumentException: The connection string contains an invalid host 'resql:'. The port '' is not a valid, it must be an integer between 0 and 65535
            at com.mongodb.ConnectionString.validatePort(ConnectionString.java:1020)
            at com.mongodb.ConnectionString.parseHosts(ConnectionString.java:1000)
            at com.mongodb.ConnectionString.<init>(ConnectionString.java:344)
            at liquibase.ext.mongodb.database.MongoConnection.open(MongoConnection.java:96)
            ... 19 more> PS. i masked the db name, username, password by "xxxxxxxxxx".

If i removed the jar file, then postgresql update is working again.

Am i did something wrong?  Or I cannot use same liquibase for mongo and postgresql at the same time?

Thanks.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1162) by [Unito](https://www.unito.io/learn-more)

**Comment by alexandru-slobodcicov** [comment] 2021-02-18 15:54
Hi @kooison, I expected it to fail however not at that stage, basically there is a internal Executor which we had to implement and inject with priority. For this I will have to raise a Issue with liquibase to map MongoExecutor(NoSqlExecutor) to LiquibaseMongoDatabase only. 
From your logs looks it fails at some earlier stage and can be fixed. 
Anyway for now yes you have to separate them.

**Comment by asimghub** [comment] 2021-04-01 13:21
I am facing this issue while connecting to mongodb from Windows Power Shell.

[2021-04-01 17:50:04] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.UnsupportedDatabase
[2021-04-01 17:50:04] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.ext.mongodb.database.MongoLiquibaseDatabase
[2021-04-01 17:50:04] FINE [liquibase.database] Properties:
[2021-04-01 17:50:04] FINE [liquibase.database] Key:'password' Value:'**********'
[2021-04-01 17:50:04] FINE [liquibase.database] Key:'user' Value:''
[2021-04-01 17:50:04] FINE [liquibase.database] Connecting to the URL:'mongodb://103.26.86.150:27017/test1/myDatabase' using driver:'liquibase.ext.mongodb.database.MongoClientDriver'
[2021-04-01 17:50:04] FINE [liquibase.servicelocator] Loaded liquibase.database.DatabaseConnection instance liquibase.database.jvm.JdbcConnection
[2021-04-01 17:50:04] FINE [liquibase.servicelocator] Loaded liquibase.database.DatabaseConnection instance com.datical.liquibase.ext.database.jvm.ProJdbcConnection
[2021-04-01 17:50:04] FINE [liquibase.servicelocator] Loaded liquibase.database.DatabaseConnection instance liquibase.ext.mongodb.database.MongoConnection
Unexpected error running Liquibase: com.mongodb.ConnectionString
For more information, please use the --logLevel flag
[2021-04-01 17:50:04] SEVERE [liquibase.integration] Unexpected error running Liquibase: com.mongodb.ConnectionString
java.lang.NoClassDefFoundError: com/mongodb/ConnectionString
        at liquibase.ext.mongodb.database.MongoConnection.open(MongoConnection.java:96)
        at liquibase.database.ConnectionServiceFactory.create(ConnectionServiceFactory.java:33)
        at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:214)
        at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:176)
        at liquibase.database.DatabaseFactory.openDatabase(DatabaseFactory.java:141)
        at liquibase.integration.commandline.CommandLineUtils.createDatabaseObject(CommandLineUtils.java:96)
        at liquibase.integration.commandline.Main.doMigration(Main.java:1432)
        at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:367)
        at liquibase.Scope.lambda$child$0(Scope.java:160)
        at liquibase.Scope.child(Scope.java:169)
        at liquibase.Scope.child(Scope.java:159)
        at liquibase.Scope.child(Scope.java:138)
        at liquibase.integration.commandline.Main$1.run(Main.java:366)
        at liquibase.integration.commandline.Main$1.run(Main.java:196)
        at liquibase.Scope.child(Scope.java:169)
        at liquibase.Scope.child(Scope.java:145)
        at liquibase.integration.commandline.Main.run(Main.java:196)
        at liquibase.integration.commandline.Main.main(Main.java:158)
Caused by: java.lang.ClassNotFoundException: com.mongodb.ConnectionString
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 18 more
        
Mongodb Version: 4.4.4
Jars: 
1. mongo-java-driver-3.12.8-javadoc.jar
2. liquibase-mongodb-4.3.2.jar
Liquibase Version: 4.3.2

Looking for suggestions and support in this regard.

**Comment by alexandru-slobodcicov** [comment] 2021-04-01 13:49
Hi @asimghub .Not the right issue to comment on. This one is related to Postgres cannot be updated while having mongodb jar. Looks like you don't have java-driver in your classpath. Just use your 3.x driver version. It is compatible with latest extension version.
Please see the Prerequisites section
https://github.com/liquibase/liquibase-mongodb/blob/main/README.md#prerequisites

I noticed you are mentioning in classpath lib/mongo-java-driver-3.12.8-javadoc.jar. 
That is a javadoc, please put the jar one https://repo1.maven.org/maven2/org/mongodb/mongodb-driver/3.12.8/mongodb-driver-3.12.8.jar

**Comment by alexandru-slobodcicov** [comment] 2021-04-01 13:53
And if you are not quite stick to 3.x java driver you can use the latest 
https://repo1.maven.org/maven2/org/mongodb/mongodb-driver-sync/4.2.2/mongodb-driver-sync-4.2.2.jar
<dependency>
            <groupId>org.mongodb</groupId>
            <artifactId>mongodb-driver-sync</artifactId>
            <version>${mongodb-driver.version}</version>
            <scope>compile</scope>
        </dependency>

**Comment by asimghub** [comment] 2021-04-02 10:14
Thanks @alexandru for the guide! It worked after following the pre requisites and some version switching. 

So should I reference this in a new issue as this thread isn't obviously related.

**Comment by alexandru-slobodcicov** [comment] 2021-04-02 12:53
No warries @asimghub about new issue as long as it is resolved. 
Happy to help.

**Comment by asimghub** [comment] 2021-04-02 13:19
Yeah thank you for the support and I've actually established the connection as per the below given logs but still having issue with the successful execution onwards as I am integrating liquibase for the first time that too with mongo so facing a bit issues regarding configurations.

Pls have  a look on the following code snippet and guide further how can I proceed with this.

`
[2021-04-01 19:59:56] FINE [liquibase.database] Properties:
[2021-04-01 19:59:57] FINE [liquibase.database] Key:'password' Value:'**********'
[2021-04-01 19:59:57] FINE [liquibase.database] Key:'user' Value:''
[2021-04-01 19:59:57] FINE [liquibase.database] Connecting to the URL:'mongodb://localhost:27017/test' using driver:'liquibase.ext.mongodb.database.MongoClientDriver'
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.database.DatabaseConnection instance liquibase.database.jvm.JdbcConnection
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.database.DatabaseConnection instance com.datical.liquibase.ext.database.jvm.ProJdbcConnection
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.database.DatabaseConnection instance liquibase.ext.mongodb.database.MongoConnection
[2021-04-01 19:59:57] WARNING [com.mongodb.diagnostics.logging.Loggers shouldUseSLF4J] SLF4J not found on the classpath.  Logging is disabled for the 'org.mongodb.driver' component
[2021-04-01 19:59:57] FINE [liquibase.database] Connection has been created
[2021-04-01 19:59:57] FINE [liquibase.ext] Connected to @localhost:27017
[2021-04-01 19:59:57] FINE [liquibase.ext] Not adjusting the auto commit mode; it is already false
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance liquibase.structure.core.Catalog
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance liquibase.structure.core.Column
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance liquibase.structure.core.Data
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance liquibase.structure.core.ForeignKey
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance liquibase.structure.core.Index
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance liquibase.structure.core.PrimaryKey
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance liquibase.structure.core.Schema
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance liquibase.structure.core.Sequence
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance liquibase.structure.core.StoredProcedure
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance liquibase.structure.core.Table
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance liquibase.structure.core.UniqueConstraint
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance liquibase.structure.core.View
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance com.datical.liquibase.ext.appdba.synonym.Synonym
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance com.datical.liquibase.ext.storedlogic.checkconstraint.CheckConstraint
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance com.datical.liquibase.ext.storedlogic.databasepackage.DatabasePackage
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance com.datical.liquibase.ext.storedlogic.databasepackage.DatabasePackageBody
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance com.datical.liquibase.ext.storedlogic.function.Function
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance com.datical.liquibase.ext.storedlogic.trigger.Trigger
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.command.LiquibaseCommand instance liquibase.command.core.DeactivateChangeLogCommand
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.command.LiquibaseCommand instance liquibase.command.core.DiffCommand
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.command.LiquibaseCommand instance liquibase.command.core.DiffToChangeLogCommand
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.command.LiquibaseCommand instance liquibase.command.core.DropAllCommand
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.command.LiquibaseCommand instance liquibase.command.core.ExecuteSqlCommand
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.command.LiquibaseCommand instance liquibase.command.core.GenerateChangeLogCommand
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.command.LiquibaseCommand instance liquibase.command.core.HistoryCommand
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.command.LiquibaseCommand instance liquibase.command.core.RegisterChangeLogCommand
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.command.LiquibaseCommand instance liquibase.command.core.SnapshotCommand
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.command.LiquibaseCommand instance liquibase.command.core.SyncHubCommand
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.command.LiquibaseCommand instance liquibase.sdk.convert.ConvertCommand
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.command.LiquibaseCommand instance com.datical.liquibase.ext.command.FormattedDiffCommand
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.command.LiquibaseCommand instance com.datical.liquibase.ext.command.RollbackOneChangeSetCommand
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.command.LiquibaseCommand instance com.datical.liquibase.ext.command.RollbackOneUpdateCommand
BEST PRACTICE: The changelog generated by diffChangeLog/generateChangeLog should be inspected for correctness and completeness before being deployed.
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance liquibase.snapshot.jvm.CatalogSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance liquibase.snapshot.jvm.ColumnSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance liquibase.snapshot.jvm.ColumnSnapshotGeneratorH2
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance liquibase.snapshot.jvm.ColumnSnapshotGeneratorInformix
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance liquibase.snapshot.jvm.ColumnSnapshotGeneratorOracle
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance liquibase.snapshot.jvm.ColumnSnapshotGeneratorPostgres
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance liquibase.snapshot.jvm.DataSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance liquibase.snapshot.jvm.ForeignKeySnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance liquibase.snapshot.jvm.IndexSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance liquibase.snapshot.jvm.PrimaryKeySnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance liquibase.snapshot.jvm.SchemaSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance liquibase.snapshot.jvm.SequenceSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance liquibase.snapshot.jvm.TableSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance liquibase.snapshot.jvm.UniqueConstraintSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance liquibase.snapshot.jvm.ViewSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance com.datical.liquibase.ext.appdba.synonym.SynonymSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance com.datical.liquibase.ext.storedlogic.checkconstraint.CheckConstraintSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance com.datical.liquibase.ext.storedlogic.checkconstraint.postgres.PostgresCheckConstraintSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance com.datical.liquibase.ext.storedlogic.databasepackage.PackageBodySnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance com.datical.liquibase.ext.storedlogic.databasepackage.PackageSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance com.datical.liquibase.ext.storedlogic.function.FunctionSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance com.datical.liquibase.ext.storedlogic.function.postgres.EDBPostgresFunctionSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance com.datical.liquibase.ext.storedlogic.function.postgres.PostgresFunctionSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance com.datical.liquibase.ext.storedlogic.function.mysql.MySQLFunctionSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance com.datical.liquibase.ext.storedlogic.storedproc.PostgresStoredProcedureSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance com.datical.liquibase.ext.storedlogic.storedproc.MySQLStoredProcedureSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance com.datical.liquibase.ext.storedlogic.storedproc.StoredProcedureSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance com.datical.liquibase.ext.storedlogic.trigger.TriggerSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance com.datical.liquibase.ext.storedlogic.trigger.postgres.PostgresTriggerSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.util] Computed checksum for 1617289197504 as 5f9b3c4715825a4cf29f74ffe357e11a
Unexpected error running Liquibase: java.lang.ClassCastException: class liquibase.ext.mongodb.database.MongoConnection cannot be cast to class liquibase.database.jvm.JdbcConnection (liquibase.ext.mongodb.database.MongoConnection and liquibase.database.jvm.JdbcConnection are in unnamed module of loader 'app')
For more information, please use the --logLevel flag
[2021-04-01 19:59:57] SEVERE [liquibase.integration] Unexpected error running Liquibase: java.lang.ClassCastException: class liquibase.ext.mongodb.database.MongoConnection cannot be cast to class liquibase.database.jvm.JdbcConnection (liquibase.ext.mongodb.database.MongoConnection and liquibase.database.jvm.JdbcConnection are in unnamed module of loader 'app')
liquibase.exception.LiquibaseException: liquibase.command.CommandExecutionException: java.lang.ClassCastException: class liquibase.ext.mongodb.database.MongoConnection cannot be cast to class liquibase.database.jvm.JdbcConnection (liquibase.ext.mongodb.database.MongoConnection and liquibase.database.jvm.JdbcConnection are in unnamed module of loader 'app')
        at liquibase.integration.commandline.CommandLineUtils.doGenerateChangeLog(CommandLineUtils.java:251)
        at liquibase.integration.commandline.Main.doMigration(Main.java:1542)
        at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:367)
        at liquibase.Scope.lambda$child$0(Scope.java:160)
        at liquibase.Scope.child(Scope.java:169)
        at liquibase.Scope.child(Scope.java:159)
        at liquibase.Scope.child(Scope.java:138)
        at liquibase.integration.commandline.Main$1.run(Main.java:366)
        at liquibase.integration.commandline.Main$1.run(Main.java:196)
        at liquibase.Scope.child(Scope.java:169)
        at liquibase.Scope.child(Scope.java:145)
        at liquibase.integration.commandline.Main.run(Main.java:196)
        at liquibase.integration.commandline.Main.main(Main.java:158)
Caused by: liquibase.command.CommandExecutionException: java.lang.ClassCastException: class liquibase.ext.mongodb.database.MongoConnection cannot be cast to class liquibase.database.jvm.JdbcConnection (liquibase.ext.mongodb.database.MongoConnection and liquibase.database.jvm.JdbcConnection are in unnamed module of loader 'app')
        at liquibase.command.AbstractCommand.execute(AbstractCommand.java:24)
        at liquibase.integration.commandline.CommandLineUtils.doGenerateChangeLog(CommandLineUtils.java:249)
        ... 12 more
Caused by: java.lang.ClassCastException: class liquibase.ext.mongodb.database.MongoConnection cannot be cast to class liquibase.database.jvm.JdbcConnection (liquibase.ext.mongodb.database.MongoConnection and liquibase.database.jvm.JdbcConnection are in unnamed module of loader 'app')
        at liquibase.snapshot.jvm.JdbcSnapshotGenerator.getDatabaseCatalogNames(JdbcSnapshotGenerator.java:144)
        at liquibase.snapshot.jvm.CatalogSnapshotGenerator.snapshotObject(CatalogSnapshotGenerator.java:35)
        at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:65)
        at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
        at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:315)
        at liquibase.snapshot.DatabaseSnapshot.init(DatabaseSnapshot.java:100)
        at liquibase.snapshot.DatabaseSnapshot.<init>(DatabaseSnapshot.java:59)
        at liquibase.snapshot.JdbcDatabaseSnapshot.<init>(JdbcDatabaseSnapshot.java:38)
        at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:215)
        at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:188)
        at liquibase.command.core.DiffCommand.createReferenceSnapshot(DiffCommand.java:222)
        at liquibase.command.core.DiffCommand.createDiffResult(DiffCommand.java:144)
        at liquibase.command.core.GenerateChangeLogCommand.run(GenerateChangeLogCommand.java:62)
        at liquibase.command.AbstractCommand.execute(AbstractCommand.java:19)
        ... 13 more
`

I've followed the pre-requisites and mentioned version compatibility but still facing this issue.

**Comment by alexandru-slobodcicov** [comment] 2021-04-02 14:32
@asimghub most probably you are trying a feature that is not supported. From first look into logs looks you are trying generateChangeLog to create a file from applied ChangeSets. Raised a separate issue for that. Will tag you there to provide the command you are running.

**Comment by alexandru-slobodcicov** [comment] 2021-04-05 18:01
Dependency on: 
https://github.com/liquibase/liquibase/issues/1782
https://github.com/liquibase/liquibase/issues/1783
PR raised: 
https://github.com/liquibase/liquibase/pull/1784
after release new liquibase will be able to fix

**Comment by alexandru-slobodcicov** [comment] 2021-11-05 15:17
Closing should be working as of v4.4.2

**Closed by alexandru-slobodcicov** 2021-11-05 15:17 UTC
