### ISSUE TITLE
Cannot rename collection

### ISSUE THREAD

**Issue by alkismavridis** [liquibase/liquibase-mongodb#126] opened 2021-04-21 13:53 UTC
I try to execute a rename command:

```
<ext:runCommand>
      <ext:command><![CDATA[
        {
          renameCollection: "myDb.foo",
          to: "myDb.bar"
        }
      ]]></ext:command>
    </ext:runCommand>
  </changeSet>
```

But I get the following error:  `Command failed with error 13 (Unauthorized): 'renameCollection may only be run against the admin database.'` The same command runs fine from studio3T.

Is there any step I am missing?

EDIT: The same error happens if I use `adminCommand`.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1492) by [Unito](https://www.unito.io/learn-more)

**Comment by alexandru-slobodcicov** [comment] 2021-04-24 06:48
Hi @alkismavridis it has to be used adminCommand see example : 
https://github.com/liquibase/liquibase-mongodb/blob/main/src/test/resources/liquibase/ext/changelog.admin-command.test.xml
And specifically for renaming a collection: 
https://github.com/liquibase/liquibase-mongodb/blob/main/src/test/java/liquibase/ext/mongodb/statement/AdminCommandStatementIT.java

Basically just change to : 
`<ext:adminCommand>
      <ext:command><![CDATA[
        {
          renameCollection: "myDb.foo",
          to: "myDb.bar"
        }
      ]]></ext:command>
    </ext:adminCommand>`

adminCommand does the switch do admin db and runs the command. Please ensure you are using latest extension as it was fixed in: 
https://github.com/liquibase/liquibase-mongodb/issues/111

Please note for adminCommand better to use placeholders for db name in order the scripts to be portable and could be applied to different DBs

**Comment by alexandru-slobodcicov** [comment] 2021-04-24 06:49
Closing as a duplicate of #111

**Closed by alexandru-slobodcicov** 2021-04-24 06:49 UTC
